// generated by mBlock5 for <your product>
// codes make you happy

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  pinMode(13,OUTPUT);
  while(1) {
      digitalWrite(13,1);
      _delay(1);
      digitalWrite(13,0);
      _delay(1);

      _loop();
  }

}

void _loop() {
}

void loop() {
  _loop();
}
